---
# This playbook deploys the whole application stack in this site.  

- name: configure and deploy the webservers and application code
  hosts: localhost
  remote_user: root

  roles:
    - nginx

- name: deploy MySQL and configure the databases
  hosts: localhost
  remote_user: root

  roles:
    - db